#!/bin/sh
set -e
set -u

mydir=`pwd`
backup="$HOME/.dotfiles-backup-`date +%s`"

# Backup the stuff and create symlinks
for f in $mydir/rc/*; do

  file=`basename $f`
  dest="$HOME/.$file"
  source="$mydir/rc/$file"

  if [[ -f $dest || -d $dest ]]; then
    mkdir -p $backup
    echo "Making backup of $dest in $backup"
    cp -R $dest $backup/$file
  fi
  echo "Symlinking: .$file"
  ln -fs $source $dest

done

echo "Symlinking configfiles"
ln -fs /home/peterderuijter/.dotfiles/_config/i3 /home/peterderuijter/.config/
ln -fs /home/peterderuijter/.dotfiles/_config/nvim /home/peterderuijter/.config/
ln -fs /home/peterderuijter/.dotfiles/_config/nvim/init.vim /home/peterderuijter/.vimrc
ln -fs /home/peterderuijter/.dotfiles/_config/termite /home/peterderuijter/.config/

echo "Done."
